# одна зависимая условная конструкция
if print('проверка') is None:
    ...
elif print('проверка') is None:
    ...
elif print('проверка') is None:
    ...
elif print('проверка') is None:
    ...
elif print('проверка') is None:
    ...

print()

# пять независимых друг от друга условных конструкций
if print('проверка') is None:
    ...
if print('проверка') is None:
    ...
if print('проверка') is None:
    ...
if print('проверка') is None:
    ...
if print('проверка') is None:
    ...

